### ISSUE TITLE
const `CStr::new_unchecked` to be stabilized in Rust 1.59.0

### ISSUE THREAD

**Issue by lopopolo** [upsuper/cstr#11]
Upstream Rust `std` is stabilizing a const version of `CStr::new_unchecked`:

- https://github.com/rust-lang/rust/pull/91855

Do you have interest in bumping this crate's MSRV to use this API from std once it is released? It would enable removing the `mem::transmute` code which looks pretty intense.

**Comment by upsuper** [comment]
Yes, I will do that once 1.59 reaches stable. I don't think it changes MSRV which it supports, just MSRV which it can be used in const context.

**Comment by upsuper** [comment]
Thanks for bringing this up!

**Comment by upsuper** [comment]
This has been done in https://github.com/upsuper/cstr/commit/8357a00735a1c13f3dd8927213f54ee202de40d2 but I forgot to close this ticket.
