### ISSUE TITLE
package `cstr v0.2.11` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.60.0-nightly

### ISSUE THREAD

**Issue by ArunGust** [upsuper/cstr#15]
I got error "package `cstr v0.2.11` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.60.0-nightly" after download today's nightly build
Even though my version is 

info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: checking for self-updates

  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.66.0-nightly (4a1467723 2022-09-23)

**Comment by upsuper** [comment]
It sounds like you have a rust toolchain override on rustup, possibly from the project. See https://rust-lang.github.io/rustup/overrides.html

It doesn't sound related to this crate other than that we increased the minimum required Rust version for the new version (for supporting no std).

Given the above, I'm closing this issue. If you think there is still something wrong with the crate, feel free to reopen it.
