### ISSUE TITLE
Add note to README about cstr literals in Rust version 1.77

### ISSUE THREAD

**Issue by BenBwall** [upsuper/cstr#16]
As of 1.77, C-string literals have been stabilized. It might be worthwhile to add a note to the README directing users on Rust 1.77 or later to use C-string literals instead of this crate.

**Comment by upsuper** [comment]
Thanks for the reminder. This crate has been [deprecated](https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#c-string-literals) now.
