### ISSUE TITLE
Consider removing the syn dependency

### ISSUE THREAD

**Issue by nox** [upsuper/cstr#6]
The only thing needing is the function to parse a string literal, do we really need to bring in all of syn for that? Would you consider merging a PR that duplicates syn's own function to parse a string?

**Comment by upsuper** [comment]
I'm very interested in removing `syn` dependency, but looking at the parsing [code](https://github.com/dtolnay/syn/blob/cd5fdc0f530f822446fccaf831669cd0cf4a0fc9/src/lit.rs#L891), I feel it's some non-trivial code that I don't want to maintain in this crate. (OTOH, the [code](https://github.com/dtolnay/syn/blob/cd5fdc0f530f822446fccaf831669cd0cf4a0fc9/src/ident.rs#L89) for identifier is much simpler and I'm more willing to take.)

Is it possible to split the string parsing code out from `syn` into a separate crate that `syn` and `cstr` can share?

**Comment by nox** [comment]
I seriously don't see the problem: Rust string literals aren't going to change any time soon, there is nothing to maintain here, just code to copy and paste and never touch again.

**Comment by upsuper** [comment]
I still find it hard to justify duplicating some non-trivial code. While Rust string literals may not change any time soon, `syn` may get updated to fix bugs or improve something, who knows. It seems that piece of code was last updated just 4 months ago, which is quite young.

I'm interested in why you would like to remove syn? It's such a common crate that basically every proc macro depends on, and you end up depending on it in every project with reasonable number of dependencies.

BTW I've just realized that I don't actually need `printing` feature in `syn`, so I removed that in 3b182f91ede9f52cbd88c757df7298fa9227bc43 and leave just `parsing`, which should be a smaller subset.

**Comment by upsuper** [comment]
Also we are not bringing in all of syn... just parsing really. I've turned off its default feature set.

**Comment by nox** [comment]
> I'm interested in why you would like to remove syn? It's such a common crate that basically every proc macro depends on, and you end up depending on it in every project with reasonable number of dependencies.

Because most large projects use syn, but many crates where I would use a cstr crate don't.

For example, most crates binding to third-party code don't need syn.

**Comment by upsuper** [comment]
Hmmm... okay. I'll figure it out maybe this weekend.

**Comment by nox** [comment]
Note, I opened an issue, but I'm not asking you to do such a task, if you would consider copy-pasting the code, don't do it yourself! I can do that on my own no problems, I have a lot of free time these days.

**Comment by upsuper** [comment]
I understand. I'd also like to find opportunities to practice Rust as I'm not using it in my work anymore :smile:

**Comment by upsuper** [comment]
I hand rolled a simplified parsing code with tests copied from `syn` to ensure its correctness. It would be appreciated if you can review that.
