### ISSUE TITLE
#[warn(clippy::transmute_ptr_to_ref)]

### ISSUE THREAD

**Issue by clinta** [upsuper/cstr#7]
Using the cstr macro results in the clippy warning #[warn(clippy::transmute_ptr_to_ref)]

```
warning: transmute from a pointer type (`*const std::ffi::CStr`) to a reference type (`&std::ffi::CStr`)
 --> src/main.rs:3:20
  |
3 | const FOO: &CStr = ::cstr::cstr!("foo");
  |                    ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::transmute_ptr_to_ref)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#transmute_ptr_to_ref
  = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is it possible to avoid this warning without disabling the check?

If not, is there a way to disable this lint for invocations of this macro without disabling this lint for my whole project?

**Comment by upsuper** [comment]
Thanks for reporting, fixed in 0.2.5 via adding a `#[allow]` for the specific expression.

We can't avoid it without disabling it, because dereferencing raw pointers in constants is unstable, and thus we have to rely on transmute for now, unless I'm missing something.
