### ISSUE TITLE
Including a file as a CStr

### ISSUE THREAD

**Issue by Taaitaaiger** [upsuper/cstr#8]
Hi,

I'd like to include a file as a `CStr`. The `include_str!` macro lets me include one as a `str`, but I need it to be null-terminated because it's used to call a specific FFI function that expects a null-terminated string. The `cstr!` macro fails to compile if `include_str!` is used as its input, and using a separate static for include string doesn't work because the name is converted to a `CStr` rather than its contents. Would it be possible for this crate to support this use case?

**Comment by upsuper** [comment]
Yes, I think we can support it. I would probably add a new `include_cstr` macro as making `cstr` work directly with `include_str` may not be easy.

**Comment by Taaitaaiger** [comment]
That would be wonderful, thanks!

**Comment by upsuper** [comment]
Sorry for the late reply. I just published a separate crate [include_cstr](https://crates.io/crates/include_cstr) for this purpose. Unfortunately, it currently requires nightly rustc, and also their code is a bit different, so I'm not including it in this crate. Hope it would be useful for you.

I'm going to close this issue for now. Thanks for your suggestion.
