### ISSUE TITLE
Hi and thanks for this great crate

### ISSUE THREAD

**Issue by lopopolo** [upsuper/cstr#9]
I stumbled across this PR in the Rust repository https://github.com/rust-lang/rust/pull/82057 and discovered your crate.

I recently added a `cstr` dep in Artichoke: https://github.com/artichoke/artichoke/pull/1085.

I wanted to say thank you. This crate fills a niche for me.

**Comment by upsuper** [comment]
Thank you for the kind words :slightly_smiling_face:
